# Generated by Django 5.1.2 on 2024-11-04 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0009_remove_house_is_paid'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='house',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='building.house'),
        ),
    ]
