# Generated by Django 5.1.2 on 2024-11-06 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_alter_tenant_house'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='house',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='landlord',
            field=models.ForeignKey(limit_choices_to={'role': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='tenantprofiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
