# Generated by Django 5.1.2 on 2024-11-13 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0009_remove_house_is_paid'),
        ('lease', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='house',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease', to='building.house'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='tenant',
            field=models.OneToOneField(limit_choices_to={'role': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='lease', to=settings.AUTH_USER_MODEL),
        ),
    ]
