# Generated by Django 5.1.2 on 2024-10-30 12:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The Building name', max_length=255)),
                ('address', models.CharField(help_text='The Building Address', max_length=255)),
                ('house_numbers', models.CharField(help_text='Number of houses in the building', max_length=255)),
                ('landlord', models.ForeignKey(help_text='The Building Owner', limit_choices_to={'role': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
