# Generated by Django 5.1.2 on 2024-10-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='house_numbers',
            field=models.PositiveIntegerField(help_text='Number of houses in the building'),
        ),
    ]
