# Generated by Django 5.1.2 on 2024-10-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_alter_building_house_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(help_text='The Building name', max_length=255, unique=True),
        ),
    ]
