# Generated by Django 5.1.2 on 2024-10-30 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_alter_building_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(help_text='The Building name', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('name', 'landlord')},
        ),
    ]
