# Generated by Django 5.1.2 on 2024-10-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0005_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
