# Generated by Django 5.1.2 on 2024-10-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0006_house_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='rent_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
