# Generated by Django 5.1.2 on 2024-10-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0007_alter_house_rent_due_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="house",
            name="rent_due_date",
        ),
        migrations.AddField(
            model_name="house",
            name="default_due_day",
            field=models.PositiveIntegerField(
                default=10, help_text="The default day of the month when rent is due"
            ),
        ),
    ]
