# Generated by Django 5.1.2 on 2024-11-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0008_remove_house_rent_due_date_house_default_due_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='is_paid',
        ),
    ]
